### ISSUE TITLE
iCubVillersLesNancy01 renaming

### ISSUE THREAD

**Issue by serena-ivaldi** [robotology/icub-main#321]
Hi guys,

could you change the name iCubVillersLesNancy01 in iCubNancy01? 
It sounds silly but it is like calling iCubGenova iCubMorego :)

Even though our address is Villers-les-Nancy, the town is Nancy. 

Sorry for the confusion :)

**Comment by pattacini** [comment]
cc @davidetome @robotology/icub-support-team

**Comment by pattacini** [comment]
Should be fixed via acaf2a415c5469efb90d7d6ad67f8f94cd310186.
Thanks @davidetome

**Comment by davidetome** [comment]
we still have problem using icub-cluster on their laptop. Already asked to @barbalberto @randaz81 @drdanz ;nobody can help. @pattacini have you a few minutes to take a look? @Fabrizio69

**Comment by serena-ivaldi** [comment]
thanks guys!! ++
